// Generated by CoffeeScript 1.7.1
(function() {
  var DefaultHooks, YParser,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  YParser = require('./YParser');

  DefaultHooks = (function(_super) {
    __extends(DefaultHooks, _super);

    function DefaultHooks() {
      DefaultHooks.__super__.constructor.call(this);
    }

    DefaultHooks.prototype.cleanStr = function(s) {
      var i, ret, tmp;
      ret = "";
      tmp = s.slice(1, -1);
      i = 0;
      while (i < tmp.length) {
        if (tmp[i] === '\\') {
          ret += tmp[i + 1];
          i += 2;
          continue;
        }
        ret += tmp[i];
        ++i;
      }
      return ret;
    };

    DefaultHooks.prototype.upper = function(s) {
      return s.toUpperCase();
    };

    DefaultHooks.prototype.lower = function(s) {
      return s.toLowerCase();
    };

    DefaultHooks.prototype.toNumber = function(s) {
      return +s;
    };

    DefaultHooks.prototype.debug = function(ast) {
      console.log(JSON.stringify(ast, null, 2));
      return true;
    };

    DefaultHooks.prototype.printAst = function(ast) {
      console.log(JSON.stringify(this.ast, null, 2));
      return true;
    };

    DefaultHooks.prototype.printCurrentToken = function(ast) {
      console.log(JSON.stringify(this.curToken, null, 2));
      console.log(JSON.stringify(this.tokens.length, null, 2));
      console.log(JSON.stringify(this.tokens[this.curToken], null, 2));
      return true;
    };

    return DefaultHooks;

  })(YParser);

  module.exports = DefaultHooks;

}).call(this);
